"""
Tests for seq_to_pdb.py - generating PDB files from sequences.
"""

import os
from pathlib import Path

import numpy as np
import pytest
from hydra.core.global_hydra import GlobalHydra
from omegaconf import DictConfig, open_dict

from src.seq_to_pdb import seq_to_pdb
from tests.helpers.utils import compose_config

# Create report directory if it doesn't exist
report_dir = os.environ.get("PYTEST_REPORT_DIR", "tests/")
os.makedirs(report_dir, exist_ok=True)

TEST_SEQUENCE = "PYA"

@pytest.fixture(scope="session")
def shared_tmp_path(tmp_path_factory):
    """
    Module-scoped temporary directory shared across all tests.
    This ensures PDB files generated by seq_to_pdb are available for MD tests.
    """
    return tmp_path_factory.mktemp("shared_test_data")

@pytest.fixture(scope="session")
def cfg_test_seq_to_pdb(shared_tmp_path: Path) -> DictConfig:
    """
    Hydra-composed config for seq_to_pdb tests.
    Also generates PDB files for use in MD tests.

    Args:
        shared_tmp_path: Module-scoped temporary directory path.

    Returns:
        DictConfig: Composed and patched Hydra config for the test.
    """
    # Important: clear Hydra before initializing
    GlobalHydra.instance().clear()

    cfg = compose_config(config_name="seq_to_pdb", overrides=[f"seq_name={TEST_SEQUENCE}"])

    # Override config for testing purposes
    with open_dict(cfg):
        cfg.paths.data_dir = str(shared_tmp_path / "data")
        cfg.paths.log_dir = str(shared_tmp_path / "logs")
        cfg.paths.work_dir = os.getcwd()

    # Generate PDB files once for all tests in this module
    seq_to_pdb(cfg)

    yield cfg

    # Cleanup for next param
    GlobalHydra.instance().clear()