"""
Tests for seq_to_pdb.py - generating PDB files from sequences.
"""

import os
from pathlib import Path

import numpy as np
import pytest
from hydra.core.global_hydra import GlobalHydra
from omegaconf import DictConfig, open_dict

from src.seq_to_pdb import seq_to_pdb
from tests.helpers.utils import compose_config

# Create report directory if it doesn't exist
report_dir = os.environ.get("PYTEST_REPORT_DIR", "tests/")
os.makedirs(report_dir, exist_ok=True)

TEST_SEQUENCE = "ACDEFGHIKLMNPQRSTVWY" # Full amino acid sequence

@pytest.fixture(scope="module")
def shared_tmp_path(tmp_path_factory):
    """
    Module-scoped temporary directory shared across all tests.
    This ensures PDB files generated by seq_to_pdb are available for MD tests.
    """
    return tmp_path_factory.mktemp("shared_test_data")


@pytest.fixture(scope="module")
def cfg_test_seq_to_pdb(shared_tmp_path: Path) -> DictConfig:
    """
    Hydra-composed config for seq_to_pdb tests.
    Also generates PDB files for use in MD tests.

    Args:
        shared_tmp_path: Module-scoped temporary directory path.

    Returns:
        DictConfig: Composed and patched Hydra config for the test.
    """
    # Important: clear Hydra before initializing
    GlobalHydra.instance().clear()

    cfg = compose_config(config_name="seq_to_pdb", overrides=[f"seq_name={TEST_SEQUENCE}"])

    # Override config for testing purposes
    with open_dict(cfg):
        cfg.paths.data_dir = str(shared_tmp_path / "data")
        cfg.paths.log_dir = str(shared_tmp_path / "logs")
        cfg.paths.work_dir = os.getcwd()

    # Generate PDB files once for all tests in this module
    seq_to_pdb(cfg)

    yield cfg

    # Cleanup for next param
    GlobalHydra.instance().clear()


@pytest.mark.forked  # prevents OpenMM/tLEaP issues
def test_seq_to_pdb(cfg_test_seq_to_pdb: DictConfig) -> None:
    """
    Tests that seq_to_pdb can generate PDB files from sequences.

    Asserts:
    - PDB files are created for each sequence
    - PDB files are not empty
    """
    pdb_path = Path(cfg_test_seq_to_pdb.paths.data_dir) / "pdbs" / f"{TEST_SEQUENCE}.pdb"
    assert pdb_path.exists(), f"PDB file for sequence {TEST_SEQUENCE} was not created."
    assert pdb_path.stat().st_size > 0, f"PDB file for sequence {TEST_SEQUENCE} is empty."

@pytest.fixture(scope="function")
def cfg_test_generate_md(shared_tmp_path: Path, cfg_test_seq_to_pdb: DictConfig) -> DictConfig:
    """
    Hydra-composed config for generate_md tests.
    Uses the shared tmp_path where PDB files are already generated.
    
    Note: Depends on cfg_test_seq_to_pdb to ensure PDB files are generated first.

    Args:
        shared_tmp_path: Module-scoped temporary directory path with PDB files.
        cfg_test_seq_to_pdb: Config fixture that generates PDB files (ensures it runs first).

    Returns:
        DictConfig: Composed and patched Hydra config for the test.
    """
    # Important: clear Hydra before initializing
    GlobalHydra.instance().clear()

    # PDB files are already in shared_tmp_path from cfg_test_seq_to_pdb fixture
    pdb_dir = shared_tmp_path / "data" / "pdbs"

    cfg = compose_config(
        config_name="generate_md",
        overrides=[
            f"pdb_filename={TEST_SEQUENCE}",  # Use AA sequence from example_sequences.txt
            "platform=CPU",  # Use CPU for tests to avoid GPU requirements
        ],
    )

    # Override config for testing purposes
    with open_dict(cfg):
        cfg.paths.data_dir = str(shared_tmp_path / "data")
        cfg.paths.log_dir = str(shared_tmp_path / "logs")
        cfg.paths.work_dir = os.getcwd()
        cfg.pdb_dir = str(pdb_dir)
        cfg.frame_interval = 10  # 10 fs between frames
        cfg.frames_per_chunk = 10  # Small chunks for testing
        cfg.warmup_steps = 10  # Reduced warmup for faster tests

    yield cfg

    # Cleanup for next param
    GlobalHydra.instance().clear()


@pytest.mark.forked  # prevents OpenMM issues
@pytest.mark.pipeline
def test_generate_md_basic(cfg_test_generate_md: DictConfig) -> None:
    """
    Basic test that generate_md can run a simulation.

    Asserts:
    - Simulation runs without errors
    - Chunk files are created
    - Chunk files contain expected data
    """
    generate_md(cfg_test_generate_md)

    chunks_dir = Path(cfg_test_generate_md.output_dir) / "chunks"
    assert chunks_dir.exists(), "Chunks directory not created"

    chunk_files = list(chunks_dir.glob("chunk_*.npz"))
    assert len(chunk_files) > 0, "No chunk files created"

    # Verify chunk file structure
    chunk_data = np.load(chunk_files[0])
    assert "positions" in chunk_data, "Chunk missing positions"
    assert "velocities" in chunk_data, "Chunk missing velocities"
    assert chunk_data["positions"].shape[0] > 0, "Chunk has no frames"
