# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - launcher: null
  - platform: gpu
  - paths: default
  - hydra: default
  - _self_
task_name: generate_remd
pdb_dir: ${paths.data_dir}/pdbs
seq_name: null
seq_filename: null
seq_idx: null
min_temp: 300
max_temp: 450
n_states: null
timestep_fs: 2.0
constraints: HBonds # One of: HBonds, AllBonds, HAngles, or null for no constraints
com_restraint: false # Apply force to keep COM of peptide complexes together
forcefield_files:
  - amber14-all.xml
  - implicit/obc1.xml
warmup_time_ns: 0.5 # Warmup duration in nanoseconds
frame_interval: 2_500 # How many integration steps between iterations (i.e. swap attempts and frame recordings)
time_ns: 25.0 # Total simulation time in nanoseconds
demultiplex: false # Extract per-state trajectories and swap rates after simulation
